default = false
black = [0.0, 0.0, 1.0]
white = [1.0, 1.0, 1.0]
red =  [1.0, 0.0, 0.0]
orange = [1.0, 0.5, 1.0]
yellow = [1.0, 1.0, 0.0]
green = [0.0, 1.0, 0.0]
blue = [0.0, 0.0, 1.0]
purple = [0.7, 0.0, 0.7]
pink = [1.0, 0.5, 0.8]